/*
 * RELIC BackEnd for AArch64 (ARM64), targeting macOS/Darwin
 *
 * Converts RELAX intermediate code into native AArch64 code.
 *
 * AArch64 Darwin ABI notes:
 *   Register    Classification    Notes
 *   x0-x7       argument/result   used here for library/syscall calls, mirroring PPC r3-r6 usage
 *   x8-x15      caller-saved      used here as backend scratch registers
 *   x16         dedicated         syscall number for svc #0x80 on Darwin
 *   x29         frame pointer
 *   x30 (lr)    link register     saved/restored via stp/ldp in the procedure prologue/epilogue
 *   sp          stack pointer     must remain 16-byte aligned at every public boundary (e.g. calls)
 *
 * Addressing of static data uses the standard Darwin adrp/PAGEOFF idiom, e.g.:
 *   adrp x9, symbol@PAGE
 *   ldrb w9, [x9, symbol@PAGEOFF]
 */
package org.relic;

import org.antlr.runtime.*;
import org.relic.util.*;
import java.io.*;
import java.util.*;

public class BackEndARM64 extends RelicObject
{
	static int errorCount = 0, warningCount = 0;
	static SymbolTable symbolTable;
	static QuadTable quadTable;
	static AsmTable asmTable = new AsmTable();
	static String file = null;
	static String alignment = "2";
	static String target = "arm64";
	static String infile = null, outfile = null;
	static Integer maxByteValue = 255;
	static Integer maxIntegerValue = 32767;
	static int stackOffset = 0;

	// scratch registers used by codegen (caller-saved, never used for arguments)
	static final String R1 = "x9";
	static final String R2 = "x10";
	static final String RD = "x11";
	static final String RA = "x12";
	static final String W1 = "w9";
	static final String W2 = "w10";
	static final String WD = "w11";

	private static String page(String symbol)
	{
		return symbol + "@PAGE";
	}

	private static String pageoff(String symbol)
	{
		return symbol + "@PAGEOFF";
	}

	// load the address of 'symbol' into 'reg' (64-bit register name)
	private static void loadAddress(String label, String comment, String reg, String symbol)
	{
		asmTable.add(new GNUAsmLine(label, "adrp", reg + "," + page(symbol), comment));
		asmTable.add(new GNUAsmLine(null, "add", reg + "," + reg + "," + pageoff(symbol), null));
	}

	public static void main(String[] args) throws Exception
	{
		if (args.length < 2)
		{
			showHelp();
			return;
		}

		if (processOptions(args) == 0)
		{
			if (infile == null || outfile == null)
			{
			}
			else
			{
				process(target, infile, outfile);
			}
		}
	}

	static int processOptions(String[] args)
	{
		for (int a = 0; a < args.length; a++)
		{
			if (args[a].charAt(0) == '-')
			{
				switch (args[a].charAt(1))
				{
					case 't':
						target = args[a].substring(3, args[a].length());
						break;

					default:
						System.err.println("unknown option: " + args[a]);
						return 1;
				}
			}
			else
			{
				if (infile == null)
				{
					infile = args[a];
				}
				else if (outfile == null)
				{
					outfile = args[a];
				}
			}
		}

		return 0;
	}

	public static void showHelp()
	{
		System.err.println("BackEndARM64 v" + version);
		System.err.println("usage: java org.relic.BackEndARM64 infile outfile");
	}

	public static int process(String desiredTarget, String infile, String outfile) throws Exception
	{
		ObjectInputStream s;
		StringToolbox tb = new StringToolbox();
		target = desiredTarget;

		FileInputStream in = new FileInputStream(infile);
		s = new ObjectInputStream(in);

		symbolTable = (SymbolTable)s.readObject();
		quadTable = (QuadTable)s.readObject();

		// Now that we have the symbol and quad tables, start processing
		asmTable.add(new GNUAsmLine(null, null, null, "Generated by BackEndARM64 " + version));
		asmTable.add(new GNUAsmLine(null, null, null, null));
		asmTable.add(new GNUAsmLine(null, null, null, null));
		createUninitializedDataSegment();
		asmTable.add(new GNUAsmLine(null, null, null, null));
		createInitializedDataSegment();
		asmTable.add(new GNUAsmLine(null, null, null, null));
		translate();

		asmTable.show(outfile);

		return 0;
	}

	static void createUninitializedDataSegment()
	{
		Iterator i = symbolTable.entrySet().iterator();

		asmTable.add(new GNUAsmLine(null, null, null, "Uninitalized data"));
		asmTable.add(new GNUAsmLine(null, ".data", null, null));
		asmTable.add(new GNUAsmLine(null, ".align", alignment, "align to " + (2 * new Integer(alignment).intValue()) + " byte boundary"));

		while (i.hasNext())
		{
			Map.Entry e = (Map.Entry)i.next();
			Symbol s = (Symbol)e.getValue();

			if (s.value != null)
			{
				// skip over initialized data
				continue;
			}

			if (s.type.equals("PROCEDURE") || s.type.equals("LABEL") || s.type.equals("UNKNOWN"))
			{
				// ignore the above types - they do not go in the segment
				continue;
			}

			Integer t = s.size;

			if (s.type.equals("STRING"))
			{
				t = t + 1;
			}
			asmTable.add(new GNUAsmLine(null, ".comm", s.name + "," + t.toString(), s.type));
		}
	}

	static void createInitializedDataSegment()
	{
		Iterator i = symbolTable.entrySet().iterator();
		String name, opcode, operand, comment;

		asmTable.add(new GNUAsmLine(null, null, null, "Initialized data"));
		asmTable.add(new GNUAsmLine(null, ".text", null, null));
		asmTable.add(new GNUAsmLine(null, ".align", alignment, "align to " + (2 * new Integer(alignment).intValue()) + " byte boundary"));

		while (i.hasNext())
		{
			Map.Entry e = (Map.Entry)i.next();
			Symbol s = (Symbol)e.getValue();

			if (s.value == null)
			{
				// skip over uninitialized data
				continue;
			}

			if (s.type.equals("LABEL") || s.type.equals("PROCEDURE"))
			{
				if (s.global == true)
				{
					asmTable.add(new GNUAsmLine(null, ".globl", s.name, null));
				}
				continue;
			}

			name = s.name;
			opcode = null;
			operand = s.value;
			comment = s.type;

			if (s.type.equals("STRING"))
			{
				opcode = ".ascii";
			}
			else
			if (s.type.equals("INTEGER"))
			{
				if (!quadTable.symbolIsReadOnlyConstant(s))
				{
					if (s.size > maxIntegerValue)
					{
						System.err.println("WARNING: " + s.size + " exceeds " + maxIntegerValue);
					}

					opcode = ".short";
				}
				else
				{
					// INTEGER constants are loaded immediate
					continue;
				}
			}
			else
			if (s.type.equals("BYTE"))
			{
				if (!quadTable.symbolIsReadOnlyConstant(s))
				{
					if (s.size > maxByteValue)
					{
						System.err.println("WARNING: " + s.size + " exceeds " + maxByteValue);
					}

					opcode = ".byte";
				}
				else
				{
					// BYTE constants are loaded immediate
					continue;
				}
			}
			else
			if (s.type.equals("BOOLEAN"))
			{
				if (!quadTable.symbolIsReadOnlyConstant(s))
				{
					opcode = ".byte";
					if (s.value.equals("TRUE") || s.value.equals("1"))
					{
						operand = "1";
					}
					else
					{
						operand = "0";
					}
				}
				else
				{
					continue;
				}
			}
			else
			if (s.type.equals("REAL"))
			{
				opcode = ".double";
				operand = s.value;
			}

			asmTable.add(new GNUAsmLine(s.name, opcode, operand, comment));
			if (s.type.equals("STRING"))
			{
				asmTable.add(new GNUAsmLine(null, ".byte", "0", null));
			}
		}
	}

	static void nop(Quad q)
	{
		asmTable.add(new GNUAsmLine(q.label, null, null, null));
	}

	static void gt(Quad q)
	{
		asmTable.add(new GNUAsmLine(q.label, "b", q.dst, q.comment));
	}

	// load src (either a memory operand or a read-only constant) into wreg (32-bit)
	static void loadByteOrBooleanInto(Quad q, String label, String comment, String wreg, Symbol src)
	{
		if (!quadTable.symbolIsReadOnlyConstant(src))
		{
			loadAddress(label, comment, RD, src.name);
			asmTable.add(new GNUAsmLine(null, "ldrb", wreg + ",[" + RD + "]", null));
		}
		else
		{
			if (src.value.equals("TRUE") || src.value.equals("1"))
			{
				asmTable.add(new GNUAsmLine(label, "mov", wreg + ",#1", comment));
			}
			else
			{
				asmTable.add(new GNUAsmLine(label, "mov", wreg + ",#0", comment));
			}
		}
	}

	static void logical(Quad q, String operation)
	{
		Symbol src1 = (Symbol)symbolTable.get(q.src1);
		Symbol src2 = (Symbol)symbolTable.get(q.src2);
		Symbol dst = (Symbol)symbolTable.get(q.dst);

		loadByteOrBooleanInto(q, q.label, q.comment, W1, src1);
		loadByteOrBooleanInto(q, null, null, W2, src2);
		asmTable.add(new GNUAsmLine(null, operation, WD + "," + W1 + "," + W2, null));
		// use RA, not RD: RD aliases WD (x11/w11) and would clobber the computed result
		loadAddress(null, null, RA, dst.name);
		asmTable.add(new GNUAsmLine(null, "strb", WD + ",[" + RA + "]", null));
	}

	static void _not(Quad q)
	{
		Symbol src1 = (Symbol)symbolTable.get(q.src1);

		loadByteOrBooleanInto(q, q.label, q.comment, W1, src1);
		asmTable.add(new GNUAsmLine(null, "eor", WD + "," + W1 + ",#1", null));
		// use RA, not RD: RD aliases WD (x11/w11) and would clobber the computed result
		loadAddress(null, null, RA, q.dst);
		asmTable.add(new GNUAsmLine(null, "strb", WD + ",[" + RA + "]", null));
	}

	static void _neg(Quad q)
	{
		Symbol s = (Symbol)symbolTable.get(q.dst);
		String loadop = null;
		String storeop = null;

		if (s.type.equals("BYTE"))
		{
			loadop = "ldrb";
			storeop = "strb";
		}
		else
		if (s.type.equals("INTEGER"))
		{
			loadop = "ldrh";
			storeop = "strh";
		}
		else
		if (s.type.equals("REAL"))
		{
			asmTable.add(new GNUAsmLine(null, null, null, "TODO: neg(REAL)"));
			return;
		}
		else
		{
			System.out.println("_neg() encountered an unsupported type.");
			return;
		}

		loadAddress(q.label, null, RD, q.dst);
		asmTable.add(new GNUAsmLine(null, loadop, W1 + ",[" + RD + "]", null));
		asmTable.add(new GNUAsmLine(null, "neg", W1 + "," + W1, "take twos complement"));
		asmTable.add(new GNUAsmLine(null, storeop, W1 + ",[" + RD + "]", null));
	}

	/*
	Legal additions/subtractions:

		Booleans cannot be added/subtracted

		Bytes, Integers and Reals can be added/subtracted
		BYTE +/- BYTE = 0-255
		INTEGER +/- INTEGER = -32768 to 32767
		REAL +/- REAL = REAL range
		BYTE +/- INTEGER = -32768 to 32767
		BYTE +/- REAL = REAL range
		INTEGER +/- REAL = REAL range
	*/
	static void loadArithOperand(Quad q, String label, String comment, String wreg, Symbol src)
	{
		if (!quadTable.symbolIsReadOnlyConstant(src))
		{
			String srcload = null;

			if (src.type.equals("BYTE"))
			{
				srcload = "ldrb";
			}
			else if (src.type.equals("INTEGER"))
			{
				srcload = "ldrsh";
			}
			else if (src.type.equals("REAL"))
			{
			}

			loadAddress(label, comment, RD, src.name);
			asmTable.add(new GNUAsmLine(null, srcload, wreg + ",[" + RD + "]", null));
		}
		else
		{
			asmTable.add(new GNUAsmLine(label, "mov", wreg + ",#" + src.value, comment));
		}
	}

	static void addsub(Quad q, String operation)
	{
		Symbol src1 = (Symbol)symbolTable.get(q.src1);
		Symbol src2 = (Symbol)symbolTable.get(q.src2);
		Symbol dst = (Symbol)symbolTable.get(q.dst);

		// string addition
		if (src1.type.equals("STRING"))
		{
			if (src2.type.equals("STRING") && operation.equals("add"))
			{
				loadAddress(null, null, "x0", q.src1);
				loadAddress(null, null, "x1", q.src2);
				loadAddress(null, null, "x2", q.dst);

				asmTable.add(new GNUAsmLine(null, "bl", "addstring", "addstring(src1addr, src2addr, dstaddr)"));
			}
			else
			{
				System.out.println("STRING can only be added to STRING");
			}
			return;
		}

		loadArithOperand(q, q.label, q.comment, W1, src1);
		loadArithOperand(q, null, null, W2, src2);

		asmTable.add(new GNUAsmLine(null, operation, WD + "," + W1 + "," + W2, null));
		// use RA, not RD: RD aliases WD (x11/w11) and would clobber the computed result
		loadAddress(null, null, RA, q.dst);

		if (dst.type.equals("BYTE"))
		{
			asmTable.add(new GNUAsmLine(null, "strb", WD + ",[" + RA + "]", null));
		}
		else
		if (dst.type.equals("INTEGER"))
		{
			asmTable.add(new GNUAsmLine(null, "strh", WD + ",[" + RA + "]", null));
		}
		else
		if (dst.type.equals("REAL"))
		{
			asmTable.add(new GNUAsmLine(null, null, null, "TODO: REAL = X + Y"));
		}
	}

	/* Legal multiplications:

		Booleans cannot be multiplied

		Bytes, Integers and Reals can be multiplied together
		BYTE * BYTE = 0-255
		INTEGER * INTEGER = -32768 to 32767
		REAL * REAL = REAL range
		BYTE * INTEGER = -32768 to 32767
		BYTE * REAL = REAL range
		INTEGER * REAL = REAL range
	*/
	static void multdiv(Quad q, String operation, Boolean modulo)
	{
		Symbol src1 = (Symbol)symbolTable.get(q.src1);
		Symbol src2 = (Symbol)symbolTable.get(q.src2);
		Symbol dst = (Symbol)symbolTable.get(q.dst);

		loadArithOperand(q, q.label, q.comment, W1, src1);
		loadArithOperand(q, null, null, W2, src2);

		asmTable.add(new GNUAsmLine(null, operation, WD + "," + W1 + "," + W2, null));
		if (modulo)
		{
			// wd currently holds the quotient (w1 / w2); compute the remainder: w1 - (wd * w2)
			asmTable.add(new GNUAsmLine(null, "msub", WD + "," + WD + "," + W2 + "," + W1, null));
		}
		// use RA, not RD: RD aliases WD (x11/w11) and would clobber the computed result
		loadAddress(null, null, RA, q.dst);

		if (dst.type.equals("BYTE"))
		{
			asmTable.add(new GNUAsmLine(null, "strb", WD + ",[" + RA + "]", null));
		}
		else
		if (dst.type.equals("INTEGER"))
		{
			asmTable.add(new GNUAsmLine(null, "strh", WD + ",[" + RA + "]", null));
		}
		else
		if (dst.type.equals("REAL"))
		{
			asmTable.add(new GNUAsmLine(null, null, null, "TODO: REAL = ? * ?"));
		}
	}

	static void rem(Quad q)
	{
	}

	static void stack(Quad q)
	{
		Symbol dst = (Symbol)symbolTable.get(q.dst);

		if (dst.type.equals("BOOLEAN") || dst.type.equals("BYTE"))
		{
			loadAddress(q.label, null, RD, q.dst);
			asmTable.add(new GNUAsmLine(null, "ldrb", WD + ",[" + RD + "]", null));
			asmTable.add(new GNUAsmLine(null, "sub", "sp,sp,#16", "update stack"));
			asmTable.add(new GNUAsmLine(null, "str", WD + ",[sp]", "save on stack"));
			stackOffset += 16;
		}
		else if (dst.type.equals("INTEGER"))
		{
			loadAddress(q.label, null, RD, q.dst);
			asmTable.add(new GNUAsmLine(null, "ldrsh", WD + ",[" + RD + "]", null));
			asmTable.add(new GNUAsmLine(null, "sub", "sp,sp,#16", "update stack"));
			asmTable.add(new GNUAsmLine(null, "str", WD + ",[sp]", "save on stack"));
			stackOffset += 16;
		}
		else if (dst.type.equals("REAL"))
		{
		}
	}

	static void unstack(Quad q)
	{
		Symbol dst = (Symbol)symbolTable.get(q.dst);

		if (dst == null)
		{
			// no destination -- just alter the stack
			asmTable.add(new GNUAsmLine(null, "add", "sp,sp,#16", "adjust stack"));
			stackOffset += 16;
			return;
		}
		else
		if (dst.type.equals("BOOLEAN") || dst.type.equals("BYTE"))
		{
			asmTable.add(new GNUAsmLine(q.label, "ldr", W1 + ",[sp]", null));
			loadAddress(null, null, RD, q.dst);
			asmTable.add(new GNUAsmLine(null, "strb", W1 + ",[" + RD + "]", null));
			asmTable.add(new GNUAsmLine(null, "add", "sp,sp,#16", "adjust stack"));
			stackOffset += 16;
		}
		else if (dst.type.equals("INTEGER"))
		{
			asmTable.add(new GNUAsmLine(q.label, "ldr", W1 + ",[sp]", null));
			loadAddress(null, null, RD, q.dst);
			asmTable.add(new GNUAsmLine(null, "strh", W1 + ",[" + RD + "]", null));
			asmTable.add(new GNUAsmLine(null, "add", "sp,sp,#16", "adjust stack"));
			stackOffset += 16;
		}
		else if (dst.type.equals("REAL"))
		{
		}
	}

	/* Legal copies:

		Boolean is an 8-bit value (0 = FALSE, 1 = TRUE)
		BOOLEAN = BOOLEAN

		Byte is an Unsigned 8-bit value (0-255)
		BYTE = BYTE
		BYTE = INTEGER % 256
		BYTE = REAL % 256

		Integer is a Signed 16-bit value (-32768 to 32767)
		INTEGER = BYTE
		INTEGER = INTEGER
		INTEGER = REAL % 65536

		REAL = BYTE
		REAL = INTEGER
		REAL = REAL

		STRING = STRING
	 */
	static void cp(Quad q)
	{
		Symbol src1 = (Symbol)symbolTable.get(q.src1);
		Symbol dst = (Symbol)symbolTable.get(q.dst);

		if (src1.type.equals("BOOLEAN"))
		{
			if (dst.type.equals("BOOLEAN"))
			{
				loadByteOrBooleanInto(q, q.label, q.comment, W1, src1);
				loadAddress(null, null, RD, q.dst);
				asmTable.add(new GNUAsmLine(null, "strb", W1 + ",[" + RD + "]", null));
			}
			else
			{
				System.out.println("BOOLEAN can only be assigned to BOOLEAN");
			}
			return;
		}

		else
		if (src1.type.equals("STRING"))
		{
			if (dst.type.equals("STRING"))
			{
				asmTable.add(new GNUAsmLine(null, "mov", "w0,#" + src1.size, null));
				loadAddress(null, null, "x1", q.src1);

				asmTable.add(new GNUAsmLine(null, "mov", "w2,#" + dst.size, null));
				loadAddress(null, null, "x3", q.dst);

				asmTable.add(new GNUAsmLine(null, "bl", "copystring", "copystring(srcsize, srcaddr, dstsize, dstaddr)"));
			}
			else
			{
				System.out.println("STRING can only be assigned to STRING");
			}
			return;
		}

		else
		if (src1.type.equals("REAL") || dst.type.equals("REAL"))
		{
			asmTable.add(new GNUAsmLine(null, null, null, "TODO: REAL copying is not supported yet"));
			return;
		}

		if (!quadTable.symbolIsReadOnlyConstant(src1))
		{
			String op = null;

			if (src1.type.equals("BYTE"))
			{
				op = "ldrb";
			}
			else if (src1.type.equals("INTEGER"))
			{
				op = "ldrh";
			}
			else if (src1.type.equals("REAL"))
			{
			}

			loadAddress(q.label, q.comment, RD, src1.name);
			asmTable.add(new GNUAsmLine(null, op, W1 + ",[" + RD + "]", null));
		}
		else
		{
			asmTable.add(new GNUAsmLine(q.label, "mov", W1 + ",#" + src1.value, q.comment));
		}

		String op = null;

		if (dst.type.equals("BYTE"))
		{
			op = "strb";
		}
		else
		if (dst.type.equals("INTEGER"))
		{
			op = "strh";
		}
		else
		if (dst.type.equals("REAL"))
		{
			asmTable.add(new GNUAsmLine(null, null, null, "TODO: REAL = ?"));
		}

		loadAddress(null, null, RD, q.dst);
		asmTable.add(new GNUAsmLine(null, op, W1 + ",[" + RD + "]", null));
	}

	static void gtconditional(Quad q)
	{
		String opcode = null;
		Symbol src1 = (Symbol)symbolTable.get(q.src1);
		Symbol src2 = (Symbol)symbolTable.get(q.src2);

		if (src1.type.equals("BOOLEAN"))
		{
			if (!src2.type.equals("BOOLEAN"))
			{
				System.out.println("BOOLEAN can only be compared with BOOLEAN");
			}

			loadByteOrBooleanInto(q, q.label, q.comment, W1, src1);
			loadByteOrBooleanInto(q, null, null, W2, src2);
		}
		else if (src2.type.equals("BOOLEAN"))
		{
			System.out.println("BOOLEAN can only be compared with BOOLEAN");
			return;
		}
		else
		{
			loadArithOperand(q, q.label, q.comment, W1, src1);
			loadArithOperand(q, null, null, W2, src2);
		}

		asmTable.add(new GNUAsmLine(null, "cmp", W1 + "," + W2, null));

		if (q.opcode.equals("gt>="))
		{
			opcode = "b.ge";
		}
		else
		if (q.opcode.equals("gt<="))
		{
			opcode = "b.le";
		}
		else
		if (q.opcode.equals("gt>"))
		{
			opcode = "b.gt";
		}
		else
		if (q.opcode.equals("gt<"))
		{
			opcode = "b.lt";
		}
		else
		if (q.opcode.equals("gt!="))
		{
			opcode = "b.ne";
		}
		else
		{
			opcode = "b.eq";
		}

		asmTable.add(new GNUAsmLine(null, opcode, q.dst, null));
	}

	static void relation(Quad q)
	{
		String opcode = null;
		Symbol src1 = (Symbol)symbolTable.get(q.src1);
		Symbol src2 = (Symbol)symbolTable.get(q.src2);

		if (q.opcode.equals(">"))
		{
			opcode = "b.gt";
		}
		else
		if (q.opcode.equals("<"))
		{
			opcode = "b.lt";
		}
		else
		if (q.opcode.equals(">="))
		{
			opcode = "b.ge";
		}
		else
		if (q.opcode.equals("<="))
		{
			opcode = "b.le";
		}
		else
		if (q.opcode.equals("="))
		{
			opcode = "b.eq";
		}
		else
		{
			opcode = "b.ne";
		}

		if (src1.type.equals("BOOLEAN"))
		{
			if (!src2.type.equals("BOOLEAN"))
			{
				System.out.println("BOOLEAN can only be compared with BOOLEAN");
				return;
			}

			loadByteOrBooleanInto(q, q.label, q.comment, W1, src1);
			loadByteOrBooleanInto(q, null, null, W2, src2);
		}

		else
		if (src1.type.equals("STRING"))
		{
			if (src2.type.equals("STRING"))
			{
				loadAddress(q.label, q.comment, "x0", q.src1);
				loadAddress(null, null, "x1", q.src2);
				asmTable.add(new GNUAsmLine(null, "bl", "comparestring", null));
				asmTable.add(new GNUAsmLine(null, "cmp", "w0,#0", null));
			}
			else
			{
				System.err.printf("illegal comparison: STRING to another type\n");
				System.exit(1);
			}

			String bra1s = "L" + asmTable.size();
			asmTable.add(new GNUAsmLine(null, opcode, bra1s, null));
			asmTable.add(new GNUAsmLine(null, "mov", W1 + ",#0", null));
			String bra2s = "L" + asmTable.size();
			asmTable.add(new GNUAsmLine(null, "b", bra2s, null));
			asmTable.add(new GNUAsmLine(bra1s, "mov", W1 + ",#1", null));
			asmTable.add(new GNUAsmLine(bra2s, null, null, null));
			loadAddress(null, q.comment, RD, q.dst);
			asmTable.add(new GNUAsmLine(null, "strb", W1 + ",[" + RD + "]", null));
			return;
		}

		else
		if (src1.type.equals("BYTE") || src1.type.equals("INTEGER"))
		{
			loadArithOperand(q, q.label, q.comment, W1, src1);
			loadArithOperand(q, null, null, W2, src2);
		}

		else
		if (src1.type.equals("REAL"))
		{
			// REAL relations are not yet supported by this backend
		}

		asmTable.add(new GNUAsmLine(null, "cmp", W1 + "," + W2, null));

		String bra1 = "L" + asmTable.size();
		asmTable.add(new GNUAsmLine(null, opcode, bra1, null));
		asmTable.add(new GNUAsmLine(null, "mov", W1 + ",#0", null));
		String bra2 = "L" + asmTable.size();
		asmTable.add(new GNUAsmLine(null, "b", bra2, null));
		asmTable.add(new GNUAsmLine(bra1, "mov", W1 + ",#1", null));
		asmTable.add(new GNUAsmLine(bra2, null, null, null));
		loadAddress(null, q.comment, RD, q.dst);
		asmTable.add(new GNUAsmLine(null, "strb", W1 + ",[" + RD + "]", null));
	}

	static void ret(Quad q)
	{
		asmTable.add(new GNUAsmLine(q.label, "ldp", "x29,x30,[sp],16", "tear down the stack frame"));
		asmTable.add(new GNUAsmLine(null, "ret", null, "return"));
	}

	static void _exit(Quad q)
	{
		Symbol s = (Symbol)symbolTable.get(q.dst);

		if (s.type.equals("BYTE"))
		{
			loadAddress(q.label, q.comment, RD, q.dst);
			asmTable.add(new GNUAsmLine(null, "ldrb", "w0,[" + RD + "]", null));
		}
		else
		{
			loadAddress(q.label, q.comment, RD, q.dst);
			asmTable.add(new GNUAsmLine(null, "ldr", "w0,[" + RD + "]", null));
		}
		asmTable.add(new GNUAsmLine(null, "mov", "x16,#1", "syscall number (sys_exit)"));
		asmTable.add(new GNUAsmLine(null, "svc", "#0x80", "call kernel"));
	}

	static void call(Quad q)
	{
		asmTable.add(new GNUAsmLine(null, "bl", q.dst, null));
	}

	static void stackpeek(Quad q)
	{
		Symbol dst = (Symbol)symbolTable.get(q.dst);

		// +16 accounts for this procedure's own stp x29,x30,[sp,-16]! prologue frame
		Integer stackOffset = (dst.param - 1) * 16 + 16;
		asmTable.add(new GNUAsmLine(q.label, "ldr", W1 + ",[sp," + stackOffset.toString() + "]", null));
		loadAddress(null, null, RD, q.dst);
		if (dst.type.equals("BOOLEAN") || dst.type.equals("BYTE"))
		{
			asmTable.add(new GNUAsmLine(null, "strb", W1 + ",[" + RD + "]", null));
		}
		if (dst.type.equals("INTEGER"))
		{
			asmTable.add(new GNUAsmLine(null, "strh", W1 + ",[" + RD + "]", null));
		}
		else if (dst.type.equals("REAL"))
		{
		}
	}

	static void stackpoke(Quad q)
	{
		Symbol dst = (Symbol)symbolTable.get(q.dst);

		// +16 accounts for this procedure's own stp x29,x30,[sp,-16]! prologue frame
		Integer stackOffset = (dst.param - 1) * 16 + 16;
		if (dst.type.equals("BOOLEAN") || dst.type.equals("BYTE"))
		{
			loadAddress(q.label, null, RD, q.dst);
			asmTable.add(new GNUAsmLine(null, "ldrb", W1 + ",[" + RD + "]", null));
			asmTable.add(new GNUAsmLine(null, "str", W1 + ",[sp," + stackOffset.toString() + "]", null));
		}
		else if (dst.type.equals("INTEGER"))
		{
			loadAddress(q.label, null, RD, q.dst);
			asmTable.add(new GNUAsmLine(null, "ldrsh", W1 + ",[" + RD + "]", null));
			asmTable.add(new GNUAsmLine(null, "str", W1 + ",[sp," + stackOffset.toString() + "]", null));
		}
		else if (dst.type.equals("REAL"))
		{
		}
	}

	static void translate()
	{
		asmTable.add(new GNUAsmLine(null, ".align", alignment, "align to " + (2 * new Integer(alignment).intValue()) + " byte boundary"));

		for (Iterator it = quadTable.iterator(); it.hasNext(); )
		{
			Quad q = (Quad)it.next();
			asmTable.add(new GNUAsmLine(null, null, null, q.prettyLine()));
			if (symbolTable.symbolIsProcedure(q.label))
			{
				// we're at the start of a procedure... generate prologue code
				asmTable.add(new GNUAsmLine(q.label, "stp", "x29,x30,[sp,-16]!", "set up the stack frame"));
				asmTable.add(new GNUAsmLine(null, "mov", "x29,sp", null));
				q.label = "";
			}

			if (q.opcode.equalsIgnoreCase("nop"))
			{
				nop(q);
			}
			else if (q.opcode.equalsIgnoreCase("gt"))
			{
				gt(q);
			}
			else if (q.opcode.equalsIgnoreCase("and"))
			{
				logical(q, "and");
			}
			else if (q.opcode.equalsIgnoreCase("or"))
			{
				logical(q, "orr");
			}
			else if (q.opcode.equalsIgnoreCase("not"))
			{
				_not(q);
			}
			else if (q.opcode.equalsIgnoreCase("neg"))
			{
				_neg(q);
			}
			else if (q.opcode.equalsIgnoreCase("+"))
			{
				addsub(q, "add");
			}
			else if (q.opcode.equalsIgnoreCase("-"))
			{
				addsub(q, "sub");
			}
			else if (q.opcode.equalsIgnoreCase("*"))
			{
				multdiv(q, "mul", false);
			}
			else if (q.opcode.equalsIgnoreCase("/"))
			{
				multdiv(q, "sdiv", false);
			}
			else if (q.opcode.equalsIgnoreCase("%"))
			{
				multdiv(q, "sdiv", true);
			}
			else if (q.opcode.equalsIgnoreCase("stack"))
			{
				stack(q);
			}
			else if (q.opcode.equalsIgnoreCase("unstack"))
			{
				unstack(q);
			}
			else if (q.opcode.equalsIgnoreCase("rem"))
			{
				rem(q);
			}
			else if (q.opcode.equalsIgnoreCase("cp"))
			{
				cp(q);
			}
			else
			if (q.opcode.equalsIgnoreCase("gt!=")
				|| q.opcode.equalsIgnoreCase("gt=")
				|| q.opcode.equalsIgnoreCase("gt>=")
				|| q.opcode.equalsIgnoreCase("gt<=")
				|| q.opcode.equalsIgnoreCase("gt>")
				|| q.opcode.equalsIgnoreCase("gt<")
			)
			{
				gtconditional(q);
			}
			else if (q.opcode.equalsIgnoreCase(">")
			|| q.opcode.equalsIgnoreCase("<")
			|| q.opcode.equalsIgnoreCase(">=")
			|| q.opcode.equalsIgnoreCase("<=")
			|| q.opcode.equalsIgnoreCase("=")
			|| q.opcode.equalsIgnoreCase("<>")
			)
			{
				relation(q);
			}
			else if (q.opcode.equalsIgnoreCase("ret"))
			{
				ret(q);
			}
			else if (q.opcode.equalsIgnoreCase("exit"))
			{
				_exit(q);
			}
			else if (q.opcode.equalsIgnoreCase("call"))
			{
				call(q);
			}
			else if (q.opcode.equalsIgnoreCase("stackpeek"))
			{
				stackpeek(q);
			}
			else if (q.opcode.equalsIgnoreCase("stackpoke"))
			{
				stackpoke(q);
			}
			else
			{
				System.err.printf("unknown instruction '%s'\n", q.opcode);
				System.exit(1);
			}
		}
	}
}
